services:
    app:
        build:
            context: ..
            dockerfile: ./deploy/Dockerfile
        ports:
            - "8000:8000"
        env_file: .env
        depends_on:
            - db
        restart: always

    db:
        image: postgres:18-alpine3.22
        ports:
            - "5432:5432"
        env_file: .env
        volumes:
            - /var/lib/postgresql/data/:/var/lib/postgresql/data/
        restart: always

    pgadmin:
        image: dpage/pgadmin4:9.10
        ports:
            - "8080:80"
        env_file: .env
        depends_on:
            - db
        restart: always
