services:
    app:
        build:
            context: ..
            dockerfile: ./deploy/Dockerfile
        ports:
            - "8000:8000"
        env_file: .env
        volumes:
            - ../data/:/data/
        depends_on:
            db:
                condition: service_healthy
        # restart: always

    db:
        image: postgres:18-alpine3.22
        ports:
            - "5432:5432"
        env_file: .env
        volumes:
            - postgres-data:/var/lib/postgresql/data/
        # restart: always
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
                ]
            interval: 5s
            retries: 5

    pgadmin:
        image: dpage/pgadmin4:9.10
        ports:
            - "8080:80"
        env_file: .env
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        # restart: always

volumes:
    postgres-data:
    pgadmin-data:
